// <auto-generated />
using System;
using FitnessApp.API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FitnessApp.API.Migrations
{
    [DbContext(typeof(MacrosContext))]
    [Migration("20201105190111_CreatingMacrosDatabase")]
    partial class CreatingMacrosDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FitnessApp.API.Entities.DailyMacroIntakeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Carbs")
                        .HasMaxLength(4);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<int>("Fats")
                        .HasMaxLength(4);

                    b.Property<int>("Protein")
                        .HasMaxLength(4);

                    b.Property<Guid>("UId");

                    b.HasKey("Id");

                    b.ToTable("DailyMacroIntakeHistory");
                });

            modelBuilder.Entity("FitnessApp.API.Entities.DailyMacroTargets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("CustomMacros");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<int>("RCarbs");

                    b.Property<int>("RFats");

                    b.Property<int>("RProtein");

                    b.Property<int>("TCarbs");

                    b.Property<int>("TFats");

                    b.Property<int>("TProtein");

                    b.Property<Guid>("UId");

                    b.HasKey("Id");

                    b.ToTable("DailyMacroTargets");
                });

            modelBuilder.Entity("FitnessApp.API.Entities.MealMacros", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Carbs")
                        .HasMaxLength(4);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<int>("Fats")
                        .HasMaxLength(4);

                    b.Property<string>("MealName")
                        .HasMaxLength(50);

                    b.Property<int>("Protein")
                        .HasMaxLength(4);

                    b.Property<Guid>("UId");

                    b.HasKey("Id");

                    b.ToTable("MealMacros");
                });

            modelBuilder.Entity("FitnessApp.API.Entities.SavedMeals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Carbs")
                        .HasMaxLength(4);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<int>("Fats")
                        .HasMaxLength(4);

                    b.Property<string>("MealName")
                        .HasMaxLength(50);

                    b.Property<int>("Protein")
                        .HasMaxLength(4);

                    b.Property<Guid>("UId");

                    b.HasKey("Id");

                    b.ToTable("SavedMeals");
                });

            modelBuilder.Entity("FitnessApp.API.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<int>("Frequency");

                    b.Property<int>("Gender");

                    b.Property<int>("Goal");

                    b.Property<int>("Height");

                    b.Property<int>("Type");

                    b.Property<Guid>("UId");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
